import { Images } from "assets";
import { StaticImageData } from "next/image";
import { routeConstant } from "routes/constants";

export type Product = {
  id: string;
  name: string;
  price: string;
  color: string;
  colorsAvailable: string;
  image: StaticImageData;
  hoverImage: StaticImageData;
  category: "shirts" | "trousers" | "jeans";
  isNew?: boolean;
  description: string;
  sizes: string[];
  materials: string;
  fit: string;
  productCode: string;
  modelInfo: string;
};

const products: Product[] = [
  {
    id: "1",
    name: "Beyond Streets T-Shirt",
    color: "Charcoal Grey",
    colorsAvailable: "1",
    price: "$89",
    image: Images.Product1,
    hoverImage: Images.Product2,
    category: "shirts",
    isNew: true,
    description:
      'Add some edge to your look with the Beyond Streets T-Shirt. This charcoal grey piece features a bold graphic on the back showcasing a distressed, city-inspired design with "Beyond Streets" written across it. The front of the shirt remains minimalist, with a subtle logo on the chest for added contrast. Crafted from soft, medium-weight cotton, this shirt is designed for both comfort and style, making it a must-have addition to your wardrobe.',
    sizes: ["S", "M", "L", "XL"],
    materials: "100% Cotton",
    fit: "Slightly Oversized Fit",
    productCode: "BST-001",
    modelInfo: "Model is 5'11 and 80kg, wearing size M",
  },
  {
    id: "2",
    name: "Beyond Classic Shirt",
    color: "Soft White",
    colorsAvailable: "1",
    price: "$129",
    image: Images.Product2,
    hoverImage: Images.Product3,
    category: "shirts",
    description:
      "Keep it fresh and relaxed with the Beyond Classic Shirt in soft white. This lightweight shirt features a striking contrast of black buttons that give it a modern, edgy vibe. The subtle embroidered detailing adds a touch of sophistication to the overall design. The lapels are neatly tailored, enhancing the clean, crisp look of the shirt. The breathable fabric and relaxed fit make it perfect for warmer days while keeping you stylish.",
    sizes: ["S", "M", "L", "XL"],
    materials: "100% Cotton",
    fit: "Relaxed Fit",
    productCode: "BCS-001",
    modelInfo: "Model is 5'11 and 80kg, wearing size M",
  },
  {
    id: "3",
    name: "Onyx Textured Black",
    color: "Onyx Black",
    colorsAvailable: "1",
    price: "$139",
    image: Images.Product3,
    hoverImage: Images.Product4,
    category: "shirts",
    description:
      "Keep it sleek and stylish with the Onyx Textured Black. This shirt is all about the details. The crisp, tailored lapels and perfectly positioned black buttons create a clean, sharp look that can be dressed up or down. Its lightweight, textured fabric adds an extra dimension of sophistication while offering exceptional comfort and breathability.",
    sizes: ["S", "M", "L", "XL"],
    materials: "100% Cotton",
    fit: "Relaxed Fit",
    productCode: "OTB-001",
    modelInfo: "Model is 5'11 and 80kg, wearing size M",
  },
  {
    id: "4",
    name: "Coastal Breeze Shirt",
    color: "Cadet Blue",
    colorsAvailable: "1",
    price: "$119",
    image: Images.Product4,
    hoverImage: Images.Product1,
    category: "shirts",
    description:
      "Bring effortless cool to your wardrobe with the Coastal Breeze Shirt in Soft Blue. Crafted from lightweight cotton, this shirt in Soft Blue features a subtle striped texture and contrast black buttons. Designed with a relaxed fit, it's perfect for casual, everyday wear. The chest pocket adds a functional touch, while the breathable fabric ensures comfort all day.",
    sizes: ["S", "M", "L", "XL"],
    materials: "100% Cotton",
    fit: "Relaxed Fit",
    productCode: "CBS-001",
    modelInfo: "Model is 5'6 and 70kg, wearing size M",
  },
  {
    id: "5",
    name: "Canyon Button-down Shirt",
    color: "Brown",
    colorsAvailable: "1",
    price: "$129",
    image: Images.Product1,
    hoverImage: Images.Product2,
    category: "shirts",
    description:
      "Made from lightweight cotton, this shirt features a rich brown colour with a subtle texture, giving it a modern yet relaxed look. The button-down front, paired with a front pocket, adds functional detail while the open collar and relaxed fit ensure all-day comfort. Whether you're pairing it with neutral trousers or adding a pop of colour, this shirt easily adapts to your style.",
    sizes: ["S", "M", "L", "XL"],
    materials: "100% Cotton",
    fit: "Relaxed Fit",
    productCode: "CBDS-001",
    modelInfo: "Model is 5'6 and 70kg, wearing size M",
  },
  {
    id: "6",
    name: "Desert Breeze Shirt",
    color: "Spanish Beige",
    colorsAvailable: "1",
    price: "$129",
    image: Images.Product2,
    hoverImage: Images.Product3,
    category: "shirts",
    description:
      "The Desert Breeze Shirt in Spanish Beige brings a fresh take on classic style. Made from a textured cotton fabric, this shirt offers a subtle depth to the light colour, adding sophistication to your everyday look. Featuring a relaxed fit with a button-down front, the shirt combines comfort and style effortlessly. The black contrast buttons give it a modern edge, while the breathable fabric ensures comfort, making it perfect for casual outings or laid-back events.",
    sizes: ["S", "M", "L", "XL"],
    materials: "100% Cotton",
    fit: "Relaxed Fit",
    productCode: "DBS-001",
    modelInfo: "Model is 5'11 and 80kg, wearing size M",
  },
  {
    id: "7",
    name: "Slate Grey Shirt",
    color: "Slate Grey",
    colorsAvailable: "1",
    price: "$129",
    image: Images.Product3,
    hoverImage: Images.Product4,
    category: "shirts",
    description:
      "The Slate Shirt in Slate Grey is the perfect balance of modern style and comfort. Made from soft, textured cotton, this shirt offers a unique look with a sophisticated grey tone and subtle texture. Designed with a relaxed fit, it features a button-down front with contrasting black buttons for a refined touch. Ideal for any casual occasion, the breathable fabric ensures all-day wearability while keeping your look fresh and effortless.",
    sizes: ["S", "M", "L", "XL"],
    materials: "100% Cotton",
    fit: "Relaxed Fit",
    productCode: "SGS-001",
    modelInfo: "Model is 188cm and 75kg, wearing size M",
  },
  {
    id: "8",
    name: "Crest T-Shirt",
    color: "Flat White",
    colorsAvailable: "3",
    price: "$155",
    image: Images.Product2,
    hoverImage: Images.Team2,
    category: "shirts",
    isNew: true,
    description: "Soft cotton blend t-shirt with minimalist crest design.",
    sizes: ["XS", "S", "M"],
    materials: "95% Cotton, 5% Elastane",
    fit: "Slim fit",
    productCode: "UCT-002",
    modelInfo: "Model is 5'10 and 70kg, wearing size S",
  },
  {
    id: "9",
    name: "Classic Logo Tee",
    color: "Navy Blue",
    colorsAvailable: "5",
    price: "$45",
    image: Images.Product3,
    hoverImage: Images.Team4,
    category: "shirts",
    description: "Timeless crewneck tee with subtle logo branding.",
    sizes: ["S", "M", "L", "XL", "XXL"],
    materials: "100% Organic Cotton",
    fit: "Classic fit",
    productCode: "ECN-003",
    modelInfo: "Model is 6'0 and 85kg, wearing size L",
  },
  {
    id: "10",
    name: "Athletic Fit Polo",
    color: "Charcoal",
    colorsAvailable: "4",
    price: "$65",
    image: Images.Product4,
    hoverImage: Images.Team3,
    category: "shirts",
    description: "Performance polo with moisture-wicking technology.",
    sizes: ["M", "L", "XL"],
    materials: "92% Polyester, 8% Spandex",
    fit: "Athletic fit",
    productCode: "PTT-004",
    modelInfo: "Model is 6'1 and 82kg, wearing size L",
  },
  {
    id: "11",
    name: "Premium Denim Jeans",
    color: "Dark Wash",
    colorsAvailable: "3",
    price: "$120",
    image: Images.Product1,
    hoverImage: Images.Team1,
    category: "jeans",
    description: "Slim-straight jeans with premium Japanese denim.",
    sizes: ["28", "30", "32", "34"],
    materials: "98% Cotton, 2% Elastane",
    fit: "Slim straight",
    productCode: "CD-005",
    modelInfo: "Model is 6'0 and 75kg, wearing size 32",
  },
  {
    id: "12",
    name: "Performance Hoodie",
    color: "Heather Grey",
    colorsAvailable: "6",
    price: "$85",
    image: Images.Product2,
    hoverImage: Images.CeoPlaceholder,
    category: "shirts",
    description: "Lightweight hoodie with breathable fabric technology.",
    sizes: ["S", "M", "L", "XL"],
    materials: "80% Cotton, 20% Polyester",
    fit: "Regular fit",
    productCode: "HLT-006",
    modelInfo: "Model is 5'11 and 78kg, wearing size M",
  },
  {
    id: "13",
    name: "Classic Trousers",
    color: "Camel",
    colorsAvailable: "2",
    price: "$175",
    image: Images.Product1,
    hoverImage: Images.Team2,
    category: "trousers",
    isNew: true,
    description: "Structured classic trousers with perfect fit.",
    sizes: ["30", "32", "34", "36"],
    materials: "65% Wool, 35% Polyester",
    fit: "Regular",
    productCode: "WBT-007",
    modelInfo: "Model is 6'0 and 80kg, wearing size 32",
  },
  {
    id: "14",
    name: "Casual Linen Shirt",
    color: "Dusty Rose",
    colorsAvailable: "4",
    price: "$55",
    image: Images.Product2,
    hoverImage: Images.Team4,
    category: "shirts",
    description: "Casual linen shirt perfect for summer.",
    sizes: ["XS", "S", "M"],
    materials: "100% Linen",
    fit: "Relaxed fit",
    productCode: "SLS-008",
    modelInfo: "Model is 5'9 and 68kg, wearing size S",
  },
  {
    id: "15",
    name: "High-Waisted Trousers",
    color: "Cream",
    colorsAvailable: "3",
    price: "$95",
    image: Images.Product3,
    hoverImage: Images.Team2,
    category: "trousers",
    description: "Tailored high-waisted trousers with front pleats.",
    sizes: ["28", "30", "32", "34"],
    materials: "55% Linen, 45% Cotton",
    fit: "High-waisted",
    productCode: "LBT-009",
    modelInfo: "Model is 5'10 and 65kg, wearing size 30",
  },
  {
    id: "16",
    name: "Oxford Dress Shirt",
    color: "White",
    colorsAvailable: "5",
    price: "$145",
    image: Images.Product4,
    hoverImage: Images.Team2,
    category: "shirts",
    description: "Classic Oxford dress shirt with perfect collar.",
    sizes: ["XS", "S", "M", "L"],
    materials: "100% Cotton",
    fit: "Classic fit",
    productCode: "VWT-010",
    modelInfo: "Model is 5'11 and 73kg, wearing size M",
  },
  {
    id: "17",
    name: "Slim Fit Jeans",
    color: "Black",
    colorsAvailable: "3",
    price: "$90",
    image: Images.Product1,
    hoverImage: Images.Team1,
    category: "jeans",
    isNew: true,
    description: "Modern slim fit jeans with stretch comfort.",
    sizes: ["28", "30", "32", "34"],
    materials: "87% Cotton, 13% Elastane",
    fit: "Slim fit",
    productCode: "SDS-011",
    modelInfo: "Model is 5'10 and 70kg, wearing size 30",
  },
  {
    id: "18",
    name: "Chino Trousers",
    color: "Khaki",
    colorsAvailable: "2",
    price: "$125",
    image: Images.Product2,
    hoverImage: Images.Team2,
    category: "trousers",
    isNew: true,
    description: "Classic chino trousers perfect for any occasion.",
    sizes: ["30", "32", "34", "36"],
    materials: "100% Cotton",
    fit: "Regular fit",
    productCode: "CT-012",
    modelInfo: "Model is 6'0 and 82kg, wearing size 34",
  },
  {
    id: "19",
    name: "Distressed Jeans",
    color: "Light Wash",
    colorsAvailable: "4",
    price: "$195",
    image: Images.Product3,
    hoverImage: Images.Team3,
    category: "jeans",
    description: "Vintage-style distressed jeans with perfect fade.",
    sizes: ["28", "30", "32", "34"],
    materials: "100% Cotton",
    fit: "Regular fit",
    productCode: "RDC-013",
    modelInfo: "Model is 6'1 and 85kg, wearing size 32",
  },
  {
    id: "20",
    name: "Dress Trousers",
    color: "Navy",
    colorsAvailable: "5",
    price: "$160",
    image: Images.Product4,
    hoverImage: Images.Team4,
    category: "trousers",
    description: "Formal dress trousers with perfect drape.",
    sizes: ["30", "32", "34", "36"],
    materials: "100% Wool",
    fit: "Classic fit",
    productCode: "WDT-014",
    modelInfo: "Model is 6'0 and 78kg, wearing size 32",
  },
  {
    id: "21",
    name: "Linen Shirt",
    color: "Sky Blue",
    colorsAvailable: "3",
    price: "$75",
    image: Images.Product1,
    hoverImage: Images.Team4,
    category: "shirts",
    description: "Breathable linen shirt with button-down collar.",
    sizes: ["S", "M", "L", "XL"],
    materials: "100% Linen",
    fit: "Relaxed fit",
    productCode: "LRS-015",
    modelInfo: "Model is 5'11 and 75kg, wearing size M",
  },
  {
    id: "22",
    name: "Straight Leg Jeans",
    color: "Medium Wash",
    colorsAvailable: "2",
    price: "$85",
    image: Images.Product2,
    hoverImage: Images.Team3,
    category: "jeans",
    description: "Classic straight leg jeans with timeless style.",
    sizes: ["28", "30", "32", "34"],
    materials: "100% Cotton",
    fit: "Straight leg",
    productCode: "SDS-016",
    modelInfo: "Model is 6'2 and 88kg, wearing size 34",
  },
];

const headerLinks: SideBarItemPathType[] = [
  {
    path: "",
    title: routeConstant.shop.title,
    children: [
      {
        path: routeConstant.collections.path + "?shirts",
        title: routeConstant.shirts.title,
      },
      {
        path: routeConstant.collections.path + "?trousers",
        title: routeConstant.trousers.title,
      },
      {
        path: routeConstant.collections.path + "?jeans",
        title: routeConstant.jeans.title,
      },
      {
        path: routeConstant.collections.path,
        title: routeConstant.collections.title,
      },
    ],
  },
  {
    path: "",
    title: routeConstant.brand.title,
    children: [
      {
        path: routeConstant.lookbook.path,
        title: routeConstant.lookbook.title,
      },
      {
        path: routeConstant.about.path,
        title: routeConstant.about.title,
      },
    ],
  },
  {
    path: "",
    title: routeConstant.info.title,
    children: [
      {
        path: routeConstant.contact.path,
        title: routeConstant.contact.title,
      },
      {
        path: routeConstant.termsAndConditions.path,
        title: routeConstant.termsAndConditions.title,
      },
      {
        path: routeConstant.shippingAndReturns.path,
        title: routeConstant.shippingAndReturns.title,
      },
    ],
  },
];

export { headerLinks, products };
