import { Images } from "assets";
import { StaticImageData } from "next/image";
import { routeConstant } from "routes/constants";

type Product = {
  id: string;
  name: string;
  price: string;
  color: string;
  colorsAvailable: string;
  image: StaticImageData;
  hoverImage: StaticImageData;
  category?: string;
  isNew?: boolean;
  description?: string;
  sizes?: string[];
  materials?: string;
  careInstructions?: string;
  fit?: string;
  shippingInfo?: string;
};

const products: Product[] = [
  {
    id: "1",
    name: "Represent Owners Club T-Shirt",
    color: "Black",
    colorsAvailable: "10",
    price: "$15",
    image: Images.Product1,
    hoverImage: Images.Team1,
    category: "men",
    isNew: true,
    description:
      "Premium heavyweight cotton t-shirt with embroidered logo detailing.",
    sizes: ["S", "M", "L", "XL"],
    materials: "100% Cotton",
    careInstructions: "Machine wash cold, tumble dry low",
    fit: "Regular fit",
    shippingInfo: "Ships in 1-2 business days",
  },
  {
    id: "2",
    name: "Crest T-Shirt",
    color: "Flat White",
    colorsAvailable: "3",
    price: "$155",
    image: Images.Product2,
    hoverImage: Images.Team2,
    category: "women",
    isNew: true,
    description: "Soft cotton blend t-shirt with minimalist crest design.",
    sizes: ["XS", "S", "M"],
    materials: "95% Cotton, 5% Elastane",
    careInstructions: "Machine wash cold, lay flat to dry",
    fit: "Slim fit",
    shippingInfo: "Ships in 1-3 business days",
  },
  {
    id: "3",
    name: "Classic Logo Tee",
    color: "Navy Blue",
    colorsAvailable: "5",
    price: "$45",
    image: Images.Product3,
    hoverImage: Images.Team4,
    category: "men",
    description: "Timeless crewneck tee with subtle logo branding.",
    sizes: ["S", "M", "L", "XL", "XXL"],
    materials: "100% Organic Cotton",
    careInstructions: "Machine wash cold, tumble dry low",
    fit: "Classic fit",
    shippingInfo: "Ships in 2-4 business days",
  },
  {
    id: "4",
    name: "Athletic Fit Polo",
    color: "Charcoal",
    colorsAvailable: "4",
    price: "$65",
    image: Images.Product4,
    hoverImage: Images.Team3,
    category: "men",
    description: "Performance polo with moisture-wicking technology.",
    sizes: ["M", "L", "XL"],
    materials: "92% Polyester, 8% Spandex",
    careInstructions: "Machine wash cold, do not bleach",
    fit: "Athletic fit",
    shippingInfo: "Ships in 1-2 business days",
  },
  {
    id: "5",
    name: "Premium Denim Jeans",
    color: "Dark Wash",
    colorsAvailable: "3",
    price: "$120",
    image: Images.Product1,
    hoverImage: Images.Team1,
    category: "men",
    description: "Slim-straight jeans with premium Japanese denim.",
    sizes: ["28", "30", "32", "34"],
    materials: "98% Cotton, 2% Elastane",
    careInstructions: "Machine wash cold inside out, hang to dry",
    fit: "Slim straight",
    shippingInfo: "Ships in 3-5 business days",
  },
  {
    id: "6",
    name: "Performance Hoodie",
    color: "Heather Grey",
    colorsAvailable: "6",
    price: "$85",
    image: Images.Product2,
    hoverImage: Images.CeoPlaceholder,
    category: "men",
    description: "Lightweight hoodie with breathable fabric technology.",
    sizes: ["S", "M", "L", "XL"],
    materials: "80% Cotton, 20% Polyester",
    careInstructions: "Machine wash cold, tumble dry low",
    fit: "Regular fit",
    shippingInfo: "Ships in 1-2 business days",
  },
  {
    id: "7",
    name: "Oversized Blazer",
    color: "Camel",
    colorsAvailable: "2",
    price: "$175",
    image: Images.Product1,
    hoverImage: Images.Team2,
    category: "women",
    isNew: true,
    description: "Structured oversized blazer with notched lapels.",
    sizes: ["4", "6", "8", "10"],
    materials: "65% Wool, 35% Polyester",
    careInstructions: "Dry clean only",
    fit: "Oversized",
    shippingInfo: "Ships in 2-3 business days",
  },
  {
    id: "8",
    name: "Silk Camisole",
    color: "Dusty Rose",
    colorsAvailable: "4",
    price: "$55",
    image: Images.Product2,
    hoverImage: Images.Team4,
    category: "women",
    description: "Luxurious silk camisole with adjustable straps.",
    sizes: ["XS", "S", "M"],
    materials: "100% Mulberry Silk",
    careInstructions: "Hand wash cold, lay flat to dry",
    fit: "Slim fit",
    shippingInfo: "Ships in 1-3 business days",
  },
  {
    id: "9",
    name: "High-Waisted Trousers",
    color: "Cream",
    colorsAvailable: "3",
    price: "$95",
    image: Images.Product3,
    hoverImage: Images.Team2,
    category: "women",
    description: "Tailored high-waisted trousers with front pleats.",
    sizes: ["2", "4", "6", "8"],
    materials: "55% Linen, 45% Cotton",
    careInstructions: "Machine wash cold, hang to dry",
    fit: "High-waisted",
    shippingInfo: "Ships in 2-4 business days",
  },
  {
    id: "10",
    name: "Cashmere Sweater",
    color: "Oatmeal",
    colorsAvailable: "5",
    price: "$145",
    image: Images.Product4,
    hoverImage: Images.Team2,
    category: "women",
    description: "Ultra-soft cashmere sweater with ribbed detailing.",
    sizes: ["XS", "S", "M", "L"],
    materials: "100% Cashmere",
    careInstructions: "Hand wash cold, lay flat to dry",
    fit: "Relaxed fit",
    shippingInfo: "Ships in 3-5 business days",
  },
  {
    id: "11",
    name: "Tech Joggers",
    color: "Black",
    colorsAvailable: "3",
    price: "$90",
    image: Images.Product1,
    hoverImage: Images.Team1,
    category: "men",
    isNew: true,
    description: "Performance joggers with water-resistant finish.",
    sizes: ["S", "M", "L", "XL"],
    materials: "87% Nylon, 13% Spandex",
    careInstructions: "Machine wash cold, tumble dry low",
    fit: "Tapered",
    shippingInfo: "Ships in 1-2 business days",
  },
  {
    id: "12",
    name: "Wrap Midi Dress",
    color: "Emerald Green",
    colorsAvailable: "2",
    price: "$125",
    image: Images.Product2,
    hoverImage: Images.Team2,
    category: "women",
    isNew: true,
    description: "Flattering wrap dress with adjustable waist tie.",
    sizes: ["XS", "S", "M"],
    materials: "100% Viscose",
    careInstructions: "Machine wash cold, hang to dry",
    fit: "Wrap style",
    shippingInfo: "Ships in 2-3 business days",
  },
  {
    id: "13",
    name: "Leather Crossbody Bag",
    color: "Cognac",
    colorsAvailable: "4",
    price: "$195",
    image: Images.Product3,
    hoverImage: Images.Team3,
    category: "women",
    description: "Genuine leather crossbody with multiple compartments.",
    sizes: ["One Size"],
    materials: "100% Italian Leather",
    careInstructions: "Wipe clean with damp cloth",
    fit: "Adjustable strap",
    shippingInfo: "Ships in 3-5 business days",
  },
  {
    id: "14",
    name: "Chino Shorts",
    color: "Khaki",
    colorsAvailable: "5",
    price: "$60",
    image: Images.Product4,
    hoverImage: Images.Team4,
    category: "men",
    description: "Classic chino shorts with functional pockets.",
    sizes: ["30", "32", "34", "36"],
    materials: "100% Cotton Twill",
    careInstructions: "Machine wash cold, tumble dry low",
    fit: "Regular fit",
    shippingInfo: "Ships in 1-3 business days",
  },
  {
    id: "15",
    name: "Linen Shirt",
    color: "Sky Blue",
    colorsAvailable: "3",
    price: "$75",
    image: Images.Product1,
    hoverImage: Images.Team4,
    category: "men",
    description: "Breathable linen shirt with button-down collar.",
    sizes: ["S", "M", "L", "XL"],
    materials: "100% Linen",
    careInstructions: "Machine wash cold, hang to dry",
    fit: "Relaxed fit",
    shippingInfo: "Ships in 2-4 business days",
  },
  {
    id: "16",
    name: "Pleated Midi Skirt",
    color: "Burgundy",
    colorsAvailable: "2",
    price: "$85",
    image: Images.Product2,
    hoverImage: Images.Team3,
    category: "women",
    description: "Flowy midi skirt with delicate pleating.",
    sizes: ["XS", "S", "M"],
    materials: "100% Polyester",
    careInstructions: "Machine wash cold, hang to dry",
    fit: "A-line",
    shippingInfo: "Ships in 1-2 business days",
  },
];

const headerLinks: SideBarItemPathType[] = [
  // {
  //   path: routeConstant.collections.path + "?men",
  //   title: routeConstant.men.title,
  // },
  {
    path: "",
    title: routeConstant.shop.title,
    children: [
      {
        path: routeConstant.collections.path + "?men",
        title: routeConstant.men.title,
      },
      {
        path: routeConstant.collections.path + "?women",
        title: routeConstant.women.title,
      },
      {
        path: routeConstant.collections.path,
        title: routeConstant.collections.title,
      },
    ],
  },
  {
    path: "",
    title: routeConstant.brand.title,
    children: [
      {
        path: routeConstant.lookbook.path,
        title: routeConstant.lookbook.title,
      },
      {
        path: routeConstant.about.path,
        title: routeConstant.about.title,
      },
    ],
  },
  {
    path: "",
    title: routeConstant.info.title,
    children: [
      {
        path: routeConstant.contact.path,
        title: routeConstant.contact.title,
      },
      {
        path: routeConstant.termsAndConditions.path,
        title: routeConstant.termsAndConditions.title,
      },
      {
        path: routeConstant.shippingAndReturns.path,
        title: routeConstant.shippingAndReturns.title,
      },
    ],
  },
  // {
  //   path: routeConstant.collections.path + "?women",
  //   title: routeConstant.women.title,
  // },
  // {
  //   path: routeConstant.collections.path,
  //   title: routeConstant.collections.title,
  // },
  // {
  //   path: routeConstant.sales.path,
  //   title: routeConstant.sales.title,
  // },
];

export { headerLinks, products };
